name: Release changelog generator

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  generate-changelog:
    name: Generate and commit changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch (master)
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags --prune

      - name: Compute changelog
        id: changelog
        run: |
          TAG=${{ github.event.release.tag_name }}
          chmod +x .github/scripts/generate_changelog.sh
          OUT=$(./.github/scripts/generate_changelog.sh "$TAG" /tmp/new_changelog.md)
          echo "newfile=$OUT" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Write changelog into repository and push
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          REPO: ${{ github.repository }}
          TAG: ${{ steps.changelog.outputs.tag }}
        run: |
          NEW=/tmp/new_changelog.md
          if [ ! -f "$NEW" ]; then
            echo "No changelog generated, exiting.";
            exit 0;
          fi
          if [ -z "${TOKEN_GITHUB}" ]; then
            echo "ERROR: TOKEN_GITHUB secret is not set. Add a PAT with repo write permissions as TOKEN_GITHUB." >&2
            exit 1
          fi
          # Ensure CHANGELOG.md exists
          if [ ! -f CHANGELOG.md ]; then echo "# Changelog" > CHANGELOG.md; fi
          # Prepend new section
          (cat "$NEW" && echo "" && cat CHANGELOG.md) > /tmp/CHANGELOG_combined.md
          mv /tmp/CHANGELOG_combined.md CHANGELOG.md
          # Configure git author to avoid 'Author identity unknown' errors on runners
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): update CHANGELOG for ${TAG}" || echo "No changes to commit"
          # Push using token
          git remote set-url origin https://x-access-token:${TOKEN_GITHUB}@github.com/${REPO}.git
          git push origin HEAD:refs/heads/master
