name: CI

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master"]

jobs:
  checks:
    name: Lint, Format & Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run quick-test (format + validate)
        run: make quick-test

      - name: Install tfsec
        run: |
          echo "Installing tfsec..."
          curl -sSL "https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/tfsec /usr/local/bin/tfsec
          tfsec --version

      - name: Run tfsec (security scan)
        run: |
          echo "Running tfsec..."
          tfsec --format junit --out .github/artifacts/tfsec-results.xml || true
          tfsec || true

      - name: Upload quick-test log
        if: always()
        run: |
          mkdir -p .github/artifacts || true
          echo "quick-test finished" > .github/artifacts/quick-test.txt
